apiVersion: v1
kind: Service
metadata:
  name: my-app-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080  # Port exposed on the load balancer
      targetPort: 3000  # Port on the pods
