apiVersion: v1
kind: Service
metadata:
  name: my-app-nodeport-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 8080  # Port exposed on the service
      targetPort: 3000
      protocol: TCP
      name: http
